### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kleist0202** [JohnNesbit/CoAtNet-Pytorch#1]
I would like to know what is the license for the code in this repository. Also, can I it be used in master's thesis with proper credit?

**Comment by JohnNesbit** [comment]
Use this code however you see fit so long as you aren't breaking the licenses of the dependencies. Also, I wrote this code when I was 14 and I did not know how to validate it properly then so I would recommend using this implementation instead: https://github.com/chinhsuanwu/coatnet-pytorch/blob/master/coatnet.py. That guy's version is copied from the official code(which has since been deleted).
